version: '3.8'

services:
  # Flask backend service
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: backend
    environment:
      - FLASK_APP=app
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_ENV=development
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - '5000:5000'
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy

  # React frontend service
  frontend:
    build:
      context: ./react-vite
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      # Mount local code for development
      - ./react-vite:/app
      # Anonymous volume to prevent node_modules overwrite
      - /app/node_modules
    depends_on:
      - backend

  # PostgreSQL database service
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      # Persist database data
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
