services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - FLASK_APP=__init__.py
      - FLASK_DEBUG=1
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SCHEMA=${SCHEMA}
      - REFRESH_DB=${REFRESH_DB:-false}
    ports:
      - '5000:5000'
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  frontend:
    build:
      context: ./react-vite
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '5173:5173'
    volumes:
      - ./react-vite:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: postgres:14-alpine
    container_name: mod7_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
volumes:
  postgres_data:

