name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main
      - your-test-branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: raspberry-pi

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create SSH directory
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Setup SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add Raspberry Pi to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.PI_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to Raspberry Pi
        env:
          PI_USER: ${{ secrets.PI_USER }}
          PI_HOST: ${{ secrets.PI_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no $PI_USER@$PI_HOST "mkdir -p ~/Mod7"
          scp -o StrictHostKeyChecking=no -r ./* $PI_USER@$PI_HOST:~/Mod7/
          ssh -o StrictHostKeyChecking=no $PI_USER@$PI_HOST "cd ~/Mod7 && chmod +x deploy.sh && ./deploy.sh"